brews:
  - name: checksum
    github:
      owner: teran
      name: homebrew-tap
    ids:
      - default
    commit_author:
      name: "Igor Shishkin"
      email: me@teran.ru
    url_template: "https://github.com/teran/checksum/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    homepage: "https://github.com/teran/checksum"
    description: "SHA256 file verification for consistency check purposes"
    test: |
      system "#{bin}/checksum --version"
    install: |
      bin.install "checksum"
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
    - arm
    - arm64
archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macOS
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
signs:
  - artifacts: checksum
