---
name: release

on:
  push:
    tags:        
      - 'v*'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: articulate/actions-markdownlint@v1

  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod download
      - name: Test with the Go CLI
        run: go test ./...
      - name: Build
        run: go build -v ./...

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - markdownlint
      - unittests
    steps:
      - name: Define build timestamp
        id: timestamp
        run: echo "::set-output name=now::$(date -u +'%Y%m%d%H%M%S')"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod download
      - name: Build & Publish release release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
